branch-defaults:
    master:
        environment: udagram-env
        group_suffix: null
# Setting EB deploy artifact to Archive.zip
deploy:
    artifact: www/Archive.zip
global:
    application_name: udagram
    branch: null
    default_ec2_keyname: null
    default_platform: Node.js 14
    default_region: us-east-1
    include_git_submodules: true
    instance_profile: null
    platform_name: null
    platform_version: null
    profile: null
    repository: null
    sc: git
    workspace_type: Application
